## DEFAULT ##

default:
  - 'dev'



## DEV ##

dev:
  description: 'Firing up the whole dev environment'
  tasks:
    - 'build'
    - 'serve'



## PROD ##

prod:
  description: 'Building a production'
  tasks:
    - 'build'



## SERVE ##

serve:
  description: 'Running server tasks'
  tasks:
    - 'connect'
    - 'open'
    - 'watch'